<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Projeto || PHP 8.0</title>
</head>
<body class="container pt-3" style="background-color: #EFEFEF;">
    <section class="card card-body">
        <nav>
            <a href="/" class="btn btn-outline-dark">Home</a>
            <a href="/listar" class="btn btn-outline-dark">Listar</a>
            <a href="/novo" class="btn btn-outline-dark">Adicionar</a>
            <a href="/admin" class="btn btn-outline-dark">Configurações</a>
        </nav>
        <hr>